resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: setup env
    inputs:
      targetType: inline 
      script: >-
        go version &&
        go env -w GOPROXY=https://goproxy.cn,direct &&
        go env -w GOPATH=~/go &&
        go get -u golang.org/x/lint/golint &&
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0

  - task: Bash@3
    displayName: golint
    inputs:
      targetType: inline
      script: >-
        ~/go/bin/golint -set_exit_status ./...

  - task: Bash@3
    displayName: golangci-lint
    inputs:
      targetType: inline
      script: >-
        ~/go/bin/golangci-lint run -v ./...

  - task: Bash@3
    displayName: build
    inputs:
      targetType: 'inline'
      script: |
        go mod tidy &&
        mkdir -p ~/build &&
        CGO_ENABLED=0 GOOS=linux go build -tags netgo -o ~/build/server .
...

