resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: setup env
    inputs:
      targetType: inline 
      script: >-
        go version &&
        go env -w GOPROXY=https://goproxy.cn,direct &&
        go env -w GOPATH=~/go &&
        go get -u golang.org/x/lint/golint &&
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0

  - task: Bash@3
    displayName: golint
    inputs:
      targetType: inline
      script: >-
        ~/go/bin/golint -set_exit_status ./...

  - task: Bash@3
    displayName: golangci-lint
    inputs:
      targetType: inline
      script: >-
        ~/go/bin/golangci-lint run -v ./...

  - task: Bash@3
    displayName: create archive folder
    inputs:
      targetType: inline
      script: >-
        mkdir -p build/conf

  - task: Bash@3
    displayName: build binary
    inputs:
      targetType: inline
      script: >-
        go build -o ./build/server .
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: './build'
      includeRootFolder: true
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
      replaceExistingArchive: true
      verbose: true
...

