resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: golint
    inputs:
      targetType: inline
      script: >-
        # Write your commands here



        docker run --rm -v $(pwd):/data cytopia/golint -set_exit_status ./...
  - task: Bash@3
    displayName: golangci-lint
    inputs:
      targetType: inline
      script: >-
        # Write your commands here


        docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.42-alpine golangci-lint run -v ./...
  - task: Docker@2
    displayName: build
    inputs:
      repository: 'golang:1.16-alpine3.14'
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'
...

