resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
    clean: true
  - task: Bash@3
    displayName: golint
    inputs:
      targetType: inline
      script: >-
        docker run --rm -v $(pwd):/data cytopia/golint -set_exit_status ./...

  - task: Bash@3
    displayName: golangci-lint
    inputs:
      targetType: inline
      script: >-
        docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.42-alpine golangci-lint run -v ./...

  - task: Bash@3
    displayName: build
    inputs:
      targetType: inline
      script: >-
        docker build -t asdgroup8/server:latest .
...

